// Common food nutrition values are practical estimates. Branded/package-style items should be checked against the nutrition label and can be saved as custom foods.
const BUILT_IN_CREATED_AT = '2026-01-01T00:00:00.000Z';
const opt = (unit, grams) => ({ unit, grams });
const food = (id, name, arabicName, category, servingUnit, baseAmount, calories, protein, carbs, fat, aliases = [], servingOptions = []) => ({
  id,
  name,
  arabicName,
  category,
  servingUnit,
  baseAmount,
  calories,
  protein,
  carbs,
  fat,
  servingOptions,
  aliases,
  source: 'common',
  createdAt: BUILT_IN_CREATED_AT,
});

export const COMMON_FOODS = [
  food('nada-protein-milk-30g', 'Nada Protein Milk 30g', 'حليب بروتين ندى 30g', 'proteinDrinks', 'bottle', 330, 210, 30, 18, 4, ['nada protein', 'nada protein 30', 'protein milk', 'ندى بروتين', 'حليب بروتين ندى', 'ندى 30 بروتين', 'بروتين ندى', 'حليب بروتين'], [opt('bottle', 330), opt('serving', 330), opt('cup', 240)]),
  food('nada-protein-milk-40g', 'Nada Protein Milk 40g', 'حليب بروتين ندى 40g', 'proteinDrinks', 'bottle', 330, 270, 40, 22, 5, ['nada protein', 'nada protein 40', 'protein milk', 'ندى بروتين', 'حليب بروتين ندى', 'ندى 40 بروتين', 'بروتين ندى'], [opt('bottle', 330), opt('serving', 330), opt('cup', 240)]),
  food('nadec-protein-milk-30g', 'Nadec Protein Milk 30g', 'حليب بروتين نادك 30g', 'proteinDrinks', 'bottle', 330, 210, 30, 18, 4, ['nadec protein', 'nadec protein 30', 'protein milk', 'نادك بروتين', 'حليب بروتين نادك', 'نادك 30 بروتين', 'بروتين نادك'], [opt('bottle', 330), opt('serving', 330), opt('cup', 240)]),
  food('nadec-protein-milk-40g', 'Nadec Protein Milk 40g', 'حليب بروتين نادك 40g', 'proteinDrinks', 'bottle', 330, 275, 40, 23, 5, ['nadec protein', 'nadec protein 40', 'protein milk', 'نادك بروتين', 'حليب بروتين نادك', 'نادك 40 بروتين', 'بروتين نادك'], [opt('bottle', 330), opt('serving', 330), opt('cup', 240)]),
  food('almarai-protein-milk', 'Almarai Protein Milk', 'حليب بروتين المراعي', 'proteinDrinks', 'bottle', 330, 220, 30, 20, 4, ['almarai protein', 'almarai milk protein', 'protein milk', 'المراعي بروتين', 'حليب بروتين المراعي', 'بروتين المراعي'], [opt('bottle', 330), opt('serving', 330), opt('cup', 240)]),
  food('protein-shake-ready-to-drink', 'Protein shake ready-to-drink', 'مشروب بروتين جاهز', 'proteinDrinks', 'bottle', 330, 200, 25, 14, 4, ['protein shake', 'ready protein', 'protein drink', 'مشروب بروتين', 'بروتين جاهز'], [opt('bottle', 330), opt('serving', 330), opt('cup', 240)]),
  food('whey-protein-scoop', 'Whey protein scoop', 'سكوب واي بروتين', 'proteinDrinks', 'scoop', 30, 120, 24, 3, 2, ['whey', 'whey scoop', 'protein scoop', 'واي', 'واي بروتين', 'سكوب واي', 'سكوب بروتين'], [opt('scoop', 30), opt('serving', 30)]),
  food('greek-yogurt-plain', 'Greek yogurt plain', 'زبادي يوناني سادة', 'highProteinDairy', 'g', 100, 80, 10, 4, 3, ['greek yogurt', 'plain greek yogurt', 'زبادي يوناني', 'زبادي يوناني سادة'], [opt('container', 170), opt('container', 200), opt('cup', 245)]),
  food('greek-yogurt-flavored', 'Greek yogurt flavored', 'زبادي يوناني بالنكهة', 'highProteinDairy', 'g', 100, 95, 9, 12, 2, ['flavored greek yogurt', 'greek yogurt', 'زبادي يوناني', 'زبادي بالنكهة'], [opt('container', 170), opt('container', 200)]),
  food('protein-yogurt', 'Protein yogurt', 'زبادي بروتين', 'highProteinDairy', 'container', 1, 150, 20, 12, 2, ['protein yogurt', 'yogurt protein', 'high protein yogurt', 'زبادي بروتين', 'زبادي عالي البروتين'], [opt('container', 200), opt('serving', 200)]),
  food('skyr-yogurt', 'Skyr yogurt', 'زبادي سكّير', 'highProteinDairy', 'g', 100, 63, 11, 4, 0, ['skyr', 'skyr yogurt', 'سكير', 'سكّير', 'زبادي سكّير'], [opt('container', 170), opt('container', 200)]),
  food('low-fat-cheese-slice', 'Low-fat cheese slice', 'شريحة جبن قليلة الدسم', 'highProteinDairy', 'slice', 1, 45, 5, 1, 2, ['low fat cheese', 'cheese slice', 'شريحة جبن', 'جبن قليل الدسم', 'جبن دايت'], [opt('slice', 20), opt('piece', 20)]),
  food('mozzarella-low-fat', 'Mozzarella low-fat', 'موزاريلا قليلة الدسم', 'highProteinDairy', 'g', 100, 200, 28, 3, 8, ['low fat mozzarella', 'mozzarella light', 'موزاريلا قليلة الدسم', 'موزاريلا لايت']),
  food('chicken-breast-raw', 'Chicken breast raw', 'صدر دجاج نيء', 'proteinFoods', 'g', 100, 120, 23, 0, 3, ['raw chicken breast', 'chicken raw', 'صدر دجاج نيء', 'دجاج نيء']),
  food('tuna-in-water', 'Tuna in water', 'تونة بالماء', 'proteinFoods', 'can', 1, 130, 29, 0, 1, ['tuna', 'tuna water', 'tuna can', 'تونة', 'تونة بالماء', 'علبة تونة'], [opt('can', 120), opt('serving', 120)]),
  food('tuna-in-oil', 'Tuna in oil', 'تونة بالزيت', 'proteinFoods', 'can', 1, 220, 27, 0, 10, ['tuna oil', 'tuna can', 'تونة بالزيت', 'علبة تونة'], [opt('can', 120), opt('serving', 120)]),
  food('turkey-slices', 'Turkey slices', 'شرائح ديك رومي', 'proteinFoods', 'slice', 1, 30, 5, 1, 1, ['turkey slices', 'turkey deli', 'شرائح ديك رومي', 'تركي سلايس'], [opt('slice', 28)]),
  food('chicken-breast-cooked', 'Chicken breast cooked', 'صدر دجاج مطبوخ', 'proteinFoods', 'g', 100, 165, 31, 0, 4, ['chicken', 'chicken breast', 'breast', 'صدر دجاج', 'دجاج', 'فراخ']),
  food('chicken-thigh-cooked', 'Chicken thigh cooked', 'فخذ دجاج مطبوخ', 'proteinFoods', 'g', 100, 209, 26, 0, 11, ['chicken thigh', 'thigh', 'فخذ', 'دجاج']),
  food('chicken-whole-cooked', 'Chicken whole cooked', 'دجاج مطبوخ', 'proteinFoods', 'g', 100, 220, 27, 0, 12, ['whole chicken', 'roasted chicken', 'دجاج', 'دجاجة']),
  food('turkey-breast-cooked', 'Turkey breast cooked', 'صدر ديك رومي', 'proteinFoods', 'g', 100, 135, 29, 0, 1, ['turkey', 'turkey breast', 'ديك رومي']),
  food('tuna-drained', 'Tuna drained', 'تونة مصفاة', 'proteinFoods', 'g', 100, 116, 26, 0, 1, ['tuna', 'drained tuna', 'تونة', 'تونا', 'مصفاة']),
  food('salmon-cooked', 'Salmon cooked', 'سلمون مطبوخ', 'proteinFoods', 'g', 100, 206, 22, 0, 12, ['salmon', 'سلمون']),
  food('shrimp-cooked', 'Shrimp cooked', 'روبيان مطبوخ', 'proteinFoods', 'g', 100, 99, 24, 0, 0, ['shrimp', 'prawns', 'روبيان', 'جمبري']),
  food('white-fish-cooked', 'White fish cooked', 'سمك أبيض مطبوخ', 'proteinFoods', 'g', 100, 105, 23, 0, 2, ['white fish', 'fish', 'سمك']),
  food('lean-beef-cooked', 'Lean beef cooked', 'لحم قليل الدهن مطبوخ', 'proteinFoods', 'g', 100, 217, 27, 0, 12, ['beef', 'lean beef', 'لحم', 'لحم قليل الدهن']),
  food('ground-beef-90-lean', 'Ground beef 90% lean', 'لحم مفروم قليل الدهن', 'proteinFoods', 'g', 100, 176, 26, 0, 8, ['ground beef', 'minced beef', '90 lean', 'لحم مفروم', 'مفروم']),
  food('egg-whole', 'Egg whole', 'بيضة كاملة', 'proteinFoods', 'piece', 50, 72, 6, 0, 5, ['egg', 'whole egg', 'بيض', 'بيضة'], [opt('piece', 50)]),
  food('egg-white', 'Egg white', 'بياض بيض', 'proteinFoods', 'piece', 33, 17, 4, 0, 0, ['egg white', 'whites', 'بياض', 'بياض بيض'], [opt('piece', 33)]),
  food('greek-yogurt-low-fat', 'Greek yogurt low-fat', 'زبادي يوناني قليل الدسم', 'proteinFoods', 'g', 100, 73, 10, 4, 2, ['greek yogurt', 'low fat greek', 'زبادي يوناني', 'زبادي بروتين'], [opt('cup', 245)]),
  food('greek-yogurt-full-fat', 'Greek yogurt full-fat', 'زبادي يوناني كامل الدسم', 'proteinFoods', 'g', 100, 97, 9, 4, 5, ['greek yogurt full fat', 'زبادي يوناني كامل']),
  food('labneh-low-fat', 'Labneh low-fat', 'لبنة قليلة الدسم', 'proteinFoods', 'g', 100, 105, 9, 5, 6, ['labneh', 'low fat labneh', 'لبنة', 'لبنه']),
  food('cottage-cheese', 'Cottage cheese', 'جبن قريش', 'proteinFoods', 'g', 100, 98, 11, 3, 4, ['cottage', 'cottage cheese', 'جبن قريش']),
  food('whey-protein-powder', 'Protein powder whey', 'واي بروتين', 'proteinFoods', 'scoop', 30, 120, 24, 3, 2, ['whey', 'protein powder', 'protein scoop', 'واي', 'واي بروتين', 'بروتين'], [opt('scoop', 30), opt('serving', 30)]),
  food('tofu', 'Tofu', 'توفو', 'proteinFoods', 'g', 100, 76, 8, 2, 5, ['tofu', 'توفو']),
  food('white-rice-cooked', 'White rice cooked', 'رز أبيض مطبوخ', 'carbFoods', 'g', 100, 130, 3, 28, 0, ['rice', 'white rice', 'cooked rice', 'رز', 'رز أبيض'], [opt('cup', 158)]),
  food('basmati-rice-cooked', 'Basmati rice cooked', 'رز بسمتي مطبوخ', 'carbFoods', 'g', 100, 121, 3, 25, 0, ['basmati', 'basmati rice', 'رز بسمتي', 'رز']),
  food('brown-rice-cooked', 'Brown rice cooked', 'رز أسمر مطبوخ', 'carbFoods', 'g', 100, 112, 3, 23, 1, ['brown rice', 'رز أسمر', 'رز بني'], [opt('cup', 158)]),
  food('pasta-cooked', 'Pasta cooked', 'مكرونة مطبوخة', 'carbFoods', 'g', 100, 158, 6, 31, 1, ['pasta', 'spaghetti', 'مكرونة', 'معكرونة'], [opt('cup', 140)]),
  food('potato-boiled', 'Potato boiled', 'بطاطس مسلوقة', 'carbFoods', 'g', 100, 87, 2, 20, 0, ['potato', 'boiled potato', 'بطاطس', 'بطاطا']),
  food('potato-baked', 'Potato baked', 'بطاطس مشوية', 'carbFoods', 'g', 100, 93, 3, 21, 0, ['baked potato', 'بطاطس مشوية']),
  food('sweet-potato-cooked', 'Sweet potato cooked', 'بطاطا حلوة', 'carbFoods', 'g', 100, 90, 2, 21, 0, ['sweet potato', 'بطاطا حلوة']),
  food('oats-dry', 'Oats dry', 'شوفان', 'carbFoods', 'g', 100, 389, 17, 66, 7, ['oats', 'oatmeal', 'اوتميل', 'شوفان'], [opt('cup', 80), opt('tbsp', 10)]),
  food('bread-white', 'Bread white', 'خبز أبيض', 'carbFoods', 'piece', 28, 75, 2, 14, 1, ['white bread', 'bread slice', 'خبز أبيض', 'توست'], [opt('piece', 28)]),
  food('bread-brown', 'Bread brown', 'خبز أسمر', 'carbFoods', 'piece', 32, 82, 4, 14, 1, ['brown bread', 'whole wheat bread', 'خبز أسمر', 'خبز بر']),
  food('toast-white', 'Toast white', 'توست أبيض', 'carbFoods', 'piece', 28, 75, 2, 14, 1, ['toast', 'white toast', 'توست', 'توست أبيض'], [opt('piece', 28)]),
  food('toast-brown', 'Toast brown', 'توست أسمر', 'carbFoods', 'piece', 32, 82, 4, 14, 1, ['brown toast', 'توست أسمر'], [opt('piece', 32)]),
  food('tortilla-wrap', 'Tortilla wrap', 'خبز تورتيلا', 'carbFoods', 'piece', 60, 190, 5, 31, 5, ['tortilla', 'wrap', 'تورتيلا', 'راب'], [opt('piece', 60)]),
  food('pita-bread', 'Pita bread', 'خبز عربي', 'carbFoods', 'piece', 60, 165, 6, 33, 1, ['pita', 'arabic bread', 'خبز عربي', 'خبز لبناني'], [opt('piece', 60)]),
  food('corn-flakes', 'Corn flakes', 'كورن فليكس', 'carbFoods', 'g', 100, 357, 8, 84, 0, ['corn flakes', 'cereal', 'كورن فليكس']),
  food('granola', 'Granola', 'جرانولا', 'carbFoods', 'g', 100, 471, 10, 64, 20, ['granola', 'جرانولا']),
  food('banana', 'Banana', 'موز', 'carbFoods', 'piece', 118, 105, 1, 27, 0, ['banana', 'موز'], [opt('piece', 118)]),
  food('apple', 'Apple', 'تفاح', 'carbFoods', 'piece', 180, 95, 0, 25, 0, ['apple', 'تفاح'], [opt('piece', 180)]),
  food('orange', 'Orange', 'برتقال', 'carbFoods', 'piece', 130, 62, 1, 15, 0, ['orange', 'برتقال'], [opt('piece', 130)]),
  food('grapes', 'Grapes', 'عنب', 'carbFoods', 'g', 100, 69, 1, 18, 0, ['grapes', 'عنب']),
  food('strawberries', 'Strawberries', 'فراولة', 'carbFoods', 'g', 100, 32, 1, 8, 0, ['strawberry', 'strawberries', 'فراولة']),
  food('dates', 'Dates', 'تمر', 'carbFoods', 'piece', 9, 25, 0, 7, 0, ['dates', 'date', 'تمر', 'تمور'], [opt('piece', 9)]),
  food('watermelon', 'Watermelon', 'بطيخ', 'carbFoods', 'g', 100, 30, 1, 8, 0, ['watermelon', 'بطيخ']),
  food('mango', 'Mango', 'مانجو', 'carbFoods', 'g', 100, 60, 1, 15, 0, ['mango', 'مانجو']),
  food('olive-oil', 'Olive oil', 'زيت زيتون', 'fatFoods', 'tbsp', 13.5, 119, 0, 0, 14, ['olive oil', 'زيت زيتون', 'ملعقة زيت'], [opt('tbsp', 13.5), opt('tsp', 4.5)]),
  food('butter', 'Butter', 'زبدة', 'fatFoods', 'tbsp', 14, 102, 0, 0, 12, ['butter', 'زبدة'], [opt('tbsp', 14), opt('tsp', 4.7)]),
  food('peanut-butter', 'Peanut butter', 'زبدة فول سوداني', 'fatFoods', 'tbsp', 16, 94, 4, 3, 8, ['peanut butter', 'pb', 'زبدة فول', 'زبدة فول سوداني'], [opt('tbsp', 16), opt('tsp', 5)]),
  food('almond-butter', 'Almond butter', 'زبدة لوز', 'fatFoods', 'tbsp', 16, 98, 3, 3, 9, ['almond butter', 'زبدة لوز'], [opt('tbsp', 16), opt('tsp', 5)]),
  food('almonds', 'Almonds', 'لوز', 'fatFoods', 'g', 100, 579, 21, 22, 50, ['almonds', 'لوز']),
  food('walnuts', 'Walnuts', 'جوز', 'fatFoods', 'g', 100, 654, 15, 14, 65, ['walnuts', 'جوز', 'عين جمل']),
  food('cashews', 'Cashews', 'كاجو', 'fatFoods', 'g', 100, 553, 18, 30, 44, ['cashews', 'كاجو']),
  food('pistachios', 'Pistachios', 'فستق', 'fatFoods', 'g', 100, 560, 20, 28, 45, ['pistachio', 'pistachios', 'فستق']),
  food('avocado', 'Avocado', 'أفوكادو', 'fatFoods', 'g', 100, 160, 2, 9, 15, ['avocado', 'افوكادو', 'أفوكادو']),
  food('tahini', 'Tahini', 'طحينة', 'fatFoods', 'tbsp', 15, 89, 3, 3, 8, ['tahini', 'طحينة'], [opt('tbsp', 15), opt('tsp', 5)]),
  food('mayonnaise', 'Mayonnaise', 'مايونيز', 'fatFoods', 'tbsp', 14, 94, 0, 0, 10, ['mayo', 'mayonnaise', 'مايونيز'], [opt('tbsp', 14), opt('tsp', 4.7)]),
  food('cheddar-cheese', 'Cheddar cheese', 'جبن شيدر', 'fatFoods', 'g', 100, 403, 25, 1, 33, ['cheddar', 'cheese', 'جبن شيدر'], [opt('piece', 20)]),
  food('mozzarella-cheese', 'Mozzarella cheese', 'جبن موزاريلا', 'fatFoods', 'g', 100, 280, 28, 3, 17, ['mozzarella', 'جبن موزاريلا']),
  food('cream-cheese', 'Cream cheese', 'جبن كريمي', 'fatFoods', 'tbsp', 14, 50, 1, 1, 5, ['cream cheese', 'جبن كريمي'], [opt('tbsp', 14)]),
  food('milk-low-fat', 'Milk low-fat', 'حليب قليل الدسم', 'dairyFoods', 'ml', 100, 42, 3, 5, 1, ['milk low fat', 'حليب قليل الدسم'], [opt('cup', 240)]),
  food('milk-full-fat', 'Milk full-fat', 'حليب كامل الدسم', 'dairyFoods', 'ml', 100, 61, 3, 5, 3, ['whole milk', 'full fat milk', 'حليب كامل'], [opt('cup', 240)]),
  food('milk-skimmed', 'Milk skimmed', 'حليب خالي الدسم', 'dairyFoods', 'ml', 100, 34, 3, 5, 0, ['skim milk', 'skimmed milk', 'حليب خالي'], [opt('cup', 240)]),
  food('yogurt-low-fat', 'Yogurt plain low-fat', 'زبادي قليل الدسم', 'dairyFoods', 'g', 100, 63, 5, 7, 2, ['yogurt', 'زبادي قليل']),
  food('yogurt-full-fat', 'Yogurt plain full-fat', 'زبادي كامل الدسم', 'dairyFoods', 'g', 100, 61, 4, 5, 3, ['full fat yogurt', 'زبادي كامل']),
  food('labneh', 'Labneh', 'لبنة', 'dairyFoods', 'g', 100, 150, 7, 5, 11, ['labneh', 'لبنة', 'لبنه']),
  food('cheese-slice', 'Cheese slice', 'شريحة جبن', 'dairyFoods', 'piece', 20, 65, 4, 1, 5, ['cheese slice', 'slice cheese', 'شريحة جبن'], [opt('piece', 20)]),
  food('feta-cheese', 'Feta cheese', 'جبن فيتا', 'dairyFoods', 'g', 100, 264, 14, 4, 21, ['feta', 'جبن فيتا']),
  food('kabsa-rice', 'Kabsa rice', 'رز كبسة', 'arabicFoods', 'g', 100, 170, 3, 31, 4, ['kabsa', 'kabsa rice', 'رز كبسة', 'كبسة']),
  food('kabsa-chicken', 'Kabsa chicken', 'دجاج كبسة', 'arabicFoods', 'g', 100, 215, 25, 2, 12, ['kabsa chicken', 'دجاج كبسة', 'كبسة دجاج']),
  food('mandi-rice', 'Mandi rice', 'رز مندي', 'arabicFoods', 'g', 100, 165, 3, 30, 4, ['mandi rice', 'رز مندي', 'مندي']),
  food('mandi-chicken', 'Mandi chicken', 'دجاج مندي', 'arabicFoods', 'g', 100, 220, 25, 1, 13, ['mandi chicken', 'دجاج مندي', 'مندي دجاج']),
  food('bukhari-rice', 'Bukhari rice', 'رز بخاري', 'arabicFoods', 'g', 100, 175, 3, 32, 4, ['bukhari', 'رز بخاري']),
  food('shawarma-chicken', 'Shawarma chicken', 'شاورما دجاج', 'arabicFoods', 'g', 100, 210, 18, 4, 13, ['shawarma', 'chicken shawarma', 'شاورما', 'شاورما دجاج']),
  food('shawarma-beef', 'Shawarma beef', 'شاورما لحم', 'arabicFoods', 'g', 100, 250, 17, 4, 18, ['beef shawarma', 'شاورما لحم']),
  food('falafel', 'Falafel', 'فلافل', 'arabicFoods', 'piece', 25, 80, 3, 7, 5, ['falafel', 'فلافل', 'طعمية'], [opt('piece', 25)]),
  food('hummus', 'Hummus', 'حمص', 'arabicFoods', 'g', 100, 166, 8, 14, 10, ['hummus', 'حمص']),
  food('foul', 'Foul', 'فول', 'arabicFoods', 'g', 100, 110, 7, 18, 1, ['foul', 'ful', 'فول']),
  food('tamees-bread', 'Tamees bread', 'تميس', 'arabicFoods', 'piece', 160, 430, 12, 80, 7, ['tamees', 'تميس', 'تمييس'], [opt('piece', 160)]),
  food('sambosa-cheese', 'Sambosa cheese', 'سمبوسة جبن', 'arabicFoods', 'piece', 35, 110, 3, 10, 7, ['samosa cheese', 'sambosa', 'سمبوسة جبن'], [opt('piece', 35)]),
  food('sambosa-meat', 'Sambosa meat', 'سمبوسة لحم', 'arabicFoods', 'piece', 35, 115, 5, 10, 6, ['samosa meat', 'سمبوسة لحم'], [opt('piece', 35)]),
  food('sambosa-chicken', 'Sambosa chicken', 'سمبوسة دجاج', 'arabicFoods', 'piece', 35, 105, 5, 10, 5, ['samosa chicken', 'سمبوسة دجاج'], [opt('piece', 35)]),
  food('mutabbaq', 'Mutabbaq', 'مطبق', 'arabicFoods', 'serving', 1, 550, 22, 55, 26, ['mutabbaq', 'مطبق'], [opt('serving', 250)]),
  food('gursan', 'Gursan', 'قرصان', 'arabicFoods', 'g', 100, 150, 6, 22, 5, ['gursan', 'قرصان']),
  food('jareesh', 'Jareesh', 'جريش', 'arabicFoods', 'g', 100, 120, 5, 18, 4, ['jareesh', 'جريش']),
  food('saleeg', 'Saleeg', 'سليق', 'arabicFoods', 'g', 100, 145, 6, 21, 4, ['saleeg', 'سليق']),
  food('molokhia', 'Molokhia', 'ملوخية', 'arabicFoods', 'g', 100, 65, 4, 7, 3, ['molokhia', 'ملوخية']),
  food('bamya-stew', 'Bamya stew', 'بامية', 'arabicFoods', 'g', 100, 85, 4, 8, 4, ['bamya', 'okra stew', 'بامية']),
  food('lentil-soup', 'Lentil soup', 'شوربة عدس', 'arabicFoods', 'g', 100, 70, 4, 12, 1, ['lentil soup', 'عدس', 'شوربة عدس']),
  food('protein-bar', 'Protein bar', 'بروتين بار', 'snackFoods', 'serving', 1, 210, 20, 22, 7, ['protein bar', 'بروتين بار'], [opt('serving', 60)]),
  food('indomie-pack', 'Indomie pack', 'إندومي كيس', 'snackFoods', 'pack', 1, 380, 8, 54, 15, ['indomie', 'instant noodles', 'noodles', 'ramen', 'إندومي', 'اندومي', 'نودلز', 'كيس إندومي'], [opt('pack', 80), opt('serving', 80)]),
  food('rice-cakes', 'Rice cakes', 'رايس كيك', 'snackFoods', 'piece', 9, 35, 1, 7, 0, ['rice cake', 'رايس كيك'], [opt('piece', 9)]),
  food('popcorn-air-popped', 'Popcorn air popped', 'فشار بدون زيت', 'snackFoods', 'g', 100, 387, 13, 78, 5, ['popcorn', 'air popped', 'فشار']),
  food('popcorn-with-oil', 'Popcorn with oil', 'فشار بزيت', 'snackFoods', 'g', 100, 500, 9, 58, 28, ['popcorn oil', 'فشار بزيت']),
  food('dark-chocolate', 'Dark chocolate', 'شوكولاتة داكنة', 'snackFoods', 'g', 100, 600, 8, 46, 43, ['dark chocolate', 'شوكولاتة داكنة']),
  food('milk-chocolate', 'Milk chocolate', 'شوكولاتة حليب', 'snackFoods', 'g', 100, 535, 8, 59, 30, ['milk chocolate', 'شوكولاتة حليب']),
  food('chips', 'Chips', 'شيبس', 'snackFoods', 'g', 100, 536, 7, 53, 35, ['chips', 'crisps', 'شيبس']),
  food('biscuits', 'Biscuits', 'بسكويت', 'snackFoods', 'g', 100, 480, 7, 70, 19, ['biscuits', 'cookies', 'بسكويت']),
  food('ice-cream', 'Ice cream', 'آيس كريم', 'snackFoods', 'g', 100, 207, 4, 24, 11, ['ice cream', 'ايس كريم', 'آيس كريم']),
  food('honey', 'Honey', 'عسل', 'snackFoods', 'tbsp', 21, 64, 0, 17, 0, ['honey', 'عسل'], [opt('tbsp', 21), opt('tsp', 7)]),
  food('jam', 'Jam', 'مربى', 'snackFoods', 'tbsp', 20, 56, 0, 14, 0, ['jam', 'مربى'], [opt('tbsp', 20)]),
  food('burger-beef', 'Burger beef', 'برجر لحم', 'fastFoods', 'serving', 1, 540, 28, 40, 32, ['burger', 'beef burger', 'برجر', 'برجر لحم'], [opt('serving', 220)]),
  food('burger-chicken', 'Burger chicken', 'برجر دجاج', 'fastFoods', 'serving', 1, 480, 25, 43, 23, ['chicken burger', 'برجر دجاج'], [opt('serving', 220)]),
  food('fries', 'Fries', 'بطاطس مقلية', 'fastFoods', 'g', 100, 312, 3, 41, 15, ['fries', 'french fries', 'بطاطس مقلية']),
  food('pizza-cheese', 'Pizza cheese', 'بيتزا جبن', 'fastFoods', 'piece', 107, 285, 12, 36, 10, ['cheese pizza', 'pizza', 'بيتزا جبن'], [opt('piece', 107)]),
  food('pizza-pepperoni', 'Pizza pepperoni', 'بيتزا بيبروني', 'fastFoods', 'piece', 110, 320, 13, 35, 15, ['pepperoni pizza', 'بيتزا بيبروني'], [opt('piece', 110)]),
  food('fried-chicken-piece', 'Fried chicken piece', 'قطعة دجاج مقلي', 'fastFoods', 'piece', 120, 320, 22, 10, 21, ['fried chicken', 'broast', 'بروست', 'دجاج مقلي'], [opt('piece', 120)]),
  food('chicken-nuggets', 'Chicken nuggets', 'ناجتس', 'fastFoods', 'piece', 16, 48, 2, 3, 3, ['nuggets', 'ناجتس'], [opt('piece', 16)]),
  food('doner-shawarma-wrap', 'Doner/Shawarma wrap', 'ساندويتش شاورما', 'fastFoods', 'serving', 1, 550, 28, 55, 24, ['doner', 'shawarma wrap', 'ساندويتش شاورما', 'شاورما'], [opt('serving', 250)]),
  food('subway-style-chicken-sandwich', 'Subway style chicken sandwich', 'ساندويتش دجاج', 'fastFoods', 'serving', 1, 420, 28, 52, 11, ['subway chicken', 'chicken sandwich', 'ساندويتش دجاج'], [opt('serving', 230)]),
  food('caesar-salad-with-dressing', 'Caesar salad with dressing', 'سلطة سيزر بالصوص', 'fastFoods', 'serving', 1, 430, 24, 18, 30, ['caesar salad', 'سلطة سيزر'], [opt('serving', 300)]),
  food('water', 'Water', 'ماء', 'drinkFoods', 'ml', 100, 0, 0, 0, 0, ['water', 'ماء', 'موية'], [opt('cup', 240)]),
  food('black-coffee', 'Black coffee', 'قهوة سوداء', 'drinkFoods', 'ml', 100, 2, 0, 0, 0, ['black coffee', 'coffee', 'قهوة سوداء', 'قهوة']),
  food('arabic-coffee', 'Arabic coffee', 'قهوة عربية', 'drinkFoods', 'ml', 100, 5, 0, 1, 0, ['arabic coffee', 'قهوة عربية']),
  food('latte-low-fat-milk', 'Latte low-fat milk', 'لاتيه بحليب قليل الدسم', 'drinkFoods', 'ml', 100, 45, 3, 5, 1, ['latte low fat', 'لاتيه'], [opt('cup', 240)]),
  food('latte-full-fat-milk', 'Latte full-fat milk', 'لاتيه بحليب كامل الدسم', 'drinkFoods', 'ml', 100, 62, 3, 5, 3, ['latte full fat', 'لاتيه كامل']),
  food('orange-juice', 'Orange juice', 'عصير برتقال', 'drinkFoods', 'ml', 100, 45, 1, 10, 0, ['orange juice', 'عصير برتقال'], [opt('cup', 240)]),
  food('apple-juice', 'Apple juice', 'عصير تفاح', 'drinkFoods', 'ml', 100, 46, 0, 11, 0, ['apple juice', 'عصير تفاح'], [opt('cup', 240)]),
  food('soft-drink-regular', 'Soft drink regular', 'مشروب غازي عادي', 'drinkFoods', 'ml', 100, 42, 0, 11, 0, ['soda', 'soft drink', 'cola', 'بيبسي', 'كولا', 'مشروب غازي']),
  food('soft-drink-zero', 'Soft drink zero', 'مشروب غازي دايت', 'drinkFoods', 'ml', 100, 0, 0, 0, 0, ['diet soda', 'zero soda', 'بيبسي دايت', 'زيرو']),
  food('energy-drink-regular', 'Energy drink regular', 'مشروب طاقة عادي', 'drinkFoods', 'ml', 100, 45, 0, 11, 0, ['energy drink', 'red bull', 'مشروب طاقة']),
  food('energy-drink-zero', 'Energy drink zero', 'مشروب طاقة دايت', 'drinkFoods', 'ml', 100, 5, 0, 1, 0, ['zero energy drink', 'مشروب طاقة دايت']),
  food('olive-oil-tablespoon', 'Olive oil tablespoon', 'ملعقة زيت زيتون', 'cookingFoods', 'tbsp', 13.5, 119, 0, 0, 14, ['olive oil tablespoon', 'ملعقة زيت زيتون'], [opt('tbsp', 13.5), opt('tsp', 4.5)]),
  food('vegetable-oil-tablespoon', 'Vegetable oil tablespoon', 'ملعقة زيت نباتي', 'cookingFoods', 'tbsp', 14, 120, 0, 0, 14, ['vegetable oil', 'زيت نباتي'], [opt('tbsp', 14), opt('tsp', 4.7)]),
  food('butter-tablespoon', 'Butter tablespoon', 'ملعقة زبدة', 'cookingFoods', 'tbsp', 14, 102, 0, 0, 12, ['butter tablespoon', 'ملعقة زبدة'], [opt('tbsp', 14), opt('tsp', 4.7)]),
  food('sugar', 'Sugar', 'سكر', 'cookingFoods', 'tsp', 4, 16, 0, 4, 0, ['sugar', 'سكر'], [opt('tsp', 4), opt('tbsp', 12)]),
  food('flour-white', 'Flour white', 'دقيق أبيض', 'cookingFoods', 'g', 100, 364, 10, 76, 1, ['flour', 'white flour', 'دقيق', 'دقيق أبيض'], [opt('cup', 120)]),
  food('breadcrumbs', 'Breadcrumbs', 'بقسماط', 'cookingFoods', 'g', 100, 395, 13, 72, 5, ['breadcrumbs', 'بقسماط']),
  food('tomato-sauce', 'Tomato sauce', 'صلصة طماطم', 'cookingFoods', 'tbsp', 16, 13, 1, 3, 0, ['tomato sauce', 'صلصة', 'صلصة طماطم'], [opt('tbsp', 16)]),
  food('ketchup', 'Ketchup', 'كاتشب', 'cookingFoods', 'tbsp', 17, 20, 0, 5, 0, ['ketchup', 'كاتشب'], [opt('tbsp', 17)]),
  food('bbq-sauce', 'BBQ sauce', 'صوص باربكيو', 'cookingFoods', 'tbsp', 17, 29, 0, 7, 0, ['bbq sauce', 'barbecue sauce', 'باربكيو'], [opt('tbsp', 17)]),
  food('ranch-sauce', 'Ranch sauce', 'صوص رانش', 'cookingFoods', 'tbsp', 15, 65, 0, 1, 7, ['ranch', 'ranch sauce', 'رانش'], [opt('tbsp', 15)]),
  food('garlic-sauce', 'Garlic sauce', 'صوص ثوم', 'cookingFoods', 'tbsp', 15, 90, 0, 1, 10, ['garlic sauce', 'ثوم', 'صوص ثوم'], [opt('tbsp', 15)]),
  food('soy-sauce', 'Soy sauce', 'صويا صوص', 'cookingFoods', 'tbsp', 15, 8, 1, 1, 0, ['soy sauce', 'soya sauce', 'صويا', 'صويا صوص'], [opt('tbsp', 15)]),

  food('whey-protein-vanilla', 'Whey protein vanilla', 'واي بروتين فانيلا', 'proteinSupplements', 'scoop', 30, 120, 24, 3, 2, ['whey', 'whey protein', 'vanilla whey', 'protein powder', 'protein scoop', 'سكوب بروتين', 'واي', 'واي بروتين', 'بروتين بودرة', 'فانيلا'], [opt('scoop', 30), opt('serving', 30)]),
  food('whey-protein-chocolate', 'Whey protein chocolate', 'واي بروتين شوكولاتة', 'proteinSupplements', 'scoop', 30, 125, 24, 4, 2, ['whey', 'whey protein', 'chocolate whey', 'protein powder', 'protein scoop', 'سكوب بروتين', 'واي', 'واي بروتين', 'بروتين بودرة', 'شوكولاتة'], [opt('scoop', 30), opt('serving', 30)]),
  food('whey-protein-strawberry', 'Whey protein strawberry', 'واي بروتين فراولة', 'proteinSupplements', 'scoop', 30, 120, 24, 3, 2, ['whey', 'whey protein', 'strawberry whey', 'protein powder', 'protein scoop', 'سكوب بروتين', 'واي', 'واي بروتين', 'بروتين بودرة', 'فراولة'], [opt('scoop', 30), opt('serving', 30)]),
  food('casein-protein-scoop', 'Casein protein scoop', 'سكوب كازين بروتين', 'proteinSupplements', 'scoop', 30, 120, 24, 4, 1, ['casein', 'casein protein', 'protein powder', 'protein scoop', 'كازين', 'سكوب بروتين', 'بروتين بودرة'], [opt('scoop', 30), opt('serving', 30)]),
  food('mass-gainer-scoop', 'Mass gainer scoop', 'سكوب ماس جينر', 'proteinSupplements', 'scoop', 50, 250, 15, 40, 4, ['mass gainer', 'gainer', 'protein powder', 'ماس جينر', 'جينر', 'سكوب ماس جينر'], [opt('scoop', 50), opt('serving', 50)]),
  food('protein-powder-generic', 'Protein powder generic', 'بودرة بروتين', 'proteinSupplements', 'scoop', 30, 120, 23, 4, 2, ['protein powder', 'protein scoop', 'whey', 'بروتين بودرة', 'بودرة بروتين', 'سكوب بروتين'], [opt('scoop', 30), opt('serving', 30)]),
  food('isolate-whey-protein', 'Isolate whey protein', 'واي بروتين آيزوليت', 'proteinSupplements', 'scoop', 30, 110, 25, 1, 1, ['isolate', 'whey isolate', 'isolate whey', 'protein powder', 'ايزوليت', 'آيزوليت', 'واي بروتين'], [opt('scoop', 30), opt('serving', 30)]),
  food('protein-coffee', 'Protein coffee', 'قهوة بروتين', 'proteinDrinks', 'bottle', 250, 160, 20, 14, 3, ['protein coffee', 'coffee protein', 'قهوة بروتين', 'بروتين قهوة'], [opt('bottle', 250), opt('serving', 250), opt('cup', 240)]),

  food('quark-cheese', 'Quark cheese', 'جبن كوارك', 'highProteinDairy', 'g', 100, 67, 12, 4, 0, ['quark', 'quark cheese', 'كوارك', 'جبن كوارك']),
  food('labneh-high-protein', 'Labneh high-protein', 'لبنة عالية البروتين', 'highProteinDairy', 'g', 100, 120, 12, 5, 5, ['high protein labneh', 'protein labneh', 'لبنة بروتين', 'لبنة عالية البروتين']),
  food('egg-white-liquid', 'Egg white liquid', 'بياض بيض جاهز', 'highProteinDairy', 'ml', 100, 50, 11, 1, 0, ['liquid egg white', 'egg whites liquid', 'egg white carton', 'بياض بيض جاهز', 'بياض بيض سائل'], [opt('cup', 240)]),

  food('cream-of-rice', 'Cream of Rice', 'كريم أوف رايس', 'carbFoods', 'g', 100, 370, 7, 82, 1, ['cream of rice', 'cream rice', 'كريم اوف رايس', 'كريم أوف رايس', 'رز مطحون'], [opt('cup', 80), opt('serving', 50)]),
  food('oats-rolled', 'Oats rolled', 'شوفان ملفوف', 'carbFoods', 'g', 100, 389, 17, 66, 7, ['oats', 'rolled oats', 'oatmeal', 'شوفان', 'شوفان ملفوف'], [opt('cup', 80), opt('tbsp', 10)]),
  food('oats-instant', 'Oats instant', 'شوفان سريع', 'carbFoods', 'g', 100, 370, 13, 68, 7, ['oats', 'instant oats', 'oatmeal', 'شوفان', 'شوفان سريع', 'اوتميل'], [opt('cup', 80), opt('tbsp', 10)]),
  food('oatmeal-cooked', 'Oatmeal cooked', 'شوفان مطبوخ', 'carbFoods', 'g', 100, 68, 2, 12, 1, ['oatmeal cooked', 'cooked oats', 'oats', 'شوفان مطبوخ', 'شوفان']),
  food('rice-uncooked', 'Rice uncooked', 'رز نيء', 'carbFoods', 'g', 100, 365, 7, 80, 1, ['uncooked rice', 'raw rice', 'rice dry', 'رز نيء', 'رز ناشف', 'رز']),
  food('pasta-uncooked', 'Pasta uncooked', 'مكرونة نيئة', 'carbFoods', 'g', 100, 371, 13, 75, 2, ['uncooked pasta', 'dry pasta', 'pasta', 'مكرونة نيئة', 'مكرونة ناشفة']),
  food('whole-wheat-pasta-cooked', 'Whole wheat pasta cooked', 'مكرونة قمح كامل مطبوخة', 'carbFoods', 'g', 100, 149, 6, 30, 1, ['whole wheat pasta', 'pasta', 'مكرونة قمح كامل', 'مكرونة']),
  food('quinoa-cooked', 'Quinoa cooked', 'كينوا مطبوخة', 'carbFoods', 'g', 100, 120, 4, 21, 2, ['quinoa', 'cooked quinoa', 'كينوا', 'كينوا مطبوخة'], [opt('cup', 185)]),
  food('corn', 'Corn', 'ذرة', 'carbFoods', 'g', 100, 96, 3, 21, 1, ['corn', 'sweet corn', 'ذرة']),
  food('burger-bun', 'Burger bun', 'خبز برجر', 'carbFoods', 'piece', 65, 170, 6, 30, 3, ['burger bun', 'bun', 'خبز برجر', 'برجر خبز'], [opt('piece', 65)]),
  food('tortilla-small', 'Tortilla small', 'تورتيلا صغير', 'carbFoods', 'piece', 35, 110, 3, 19, 3, ['tortilla', 'small tortilla', 'تورتيلا', 'تورتيلا صغير'], [opt('piece', 35)]),
  food('tortilla-large', 'Tortilla large', 'تورتيلا كبير', 'carbFoods', 'piece', 70, 220, 6, 37, 6, ['tortilla', 'large tortilla', 'wrap', 'تورتيلا', 'تورتيلا كبير'], [opt('piece', 70)]),
  food('arabic-bread-small', 'Arabic bread small', 'خبز عربي صغير', 'carbFoods', 'piece', 45, 125, 4, 25, 1, ['arabic bread', 'pita', 'خبز عربي', 'خبز عربي صغير'], [opt('piece', 45)]),
  food('arabic-bread-large', 'Arabic bread large', 'خبز عربي كبير', 'carbFoods', 'piece', 90, 250, 8, 50, 2, ['arabic bread', 'pita', 'خبز عربي', 'خبز عربي كبير'], [opt('piece', 90)]),

  food('granola-bar', 'Granola bar', 'جرانولا بار', 'snackFoods', 'serving', 1, 140, 3, 24, 4, ['granola bar', 'granola', 'جرانولا بار', 'جرانولا'], [opt('serving', 35)]),
  food('rice-cakes-with-peanut-butter', 'Rice cakes with peanut butter', 'رايس كيك مع زبدة فول سوداني', 'snackFoods', 'serving', 1, 130, 4, 14, 7, ['rice cakes peanut butter', 'rice cake pb', 'رايس كيك', 'زبدة فول سوداني'], [opt('serving', 25)]),
  food('low-fat-chocolate', 'Low-fat chocolate', 'شوكولاتة قليلة الدسم', 'snackFoods', 'g', 100, 420, 7, 68, 12, ['low fat chocolate', 'chocolate', 'شوكولاتة', 'شوكولاتة قليلة الدسم']),

  food('coconut-oil', 'Coconut oil', 'زيت جوز الهند', 'fatFoods', 'tbsp', 14, 121, 0, 0, 14, ['coconut oil', 'زيت جوز الهند'], [opt('tbsp', 14), opt('tsp', 4.7)]),
  food('flaxseed-oil', 'Flaxseed oil', 'زيت بذور الكتان', 'fatFoods', 'tbsp', 14, 120, 0, 0, 14, ['flaxseed oil', 'flax oil', 'زيت بذور الكتان', 'زيت كتان'], [opt('tbsp', 14), opt('tsp', 4.7)]),
  food('light-margarine', 'Light margarine', 'مارجرين خفيف', 'fatFoods', 'tbsp', 14, 50, 0, 0, 5, ['light margarine', 'margarine', 'مارجرين', 'مارجرين خفيف'], [opt('tbsp', 14), opt('tsp', 4.7)]),

  food('blueberries', 'Blueberries', 'توت أزرق', 'fruitFoods', 'g', 100, 57, 1, 14, 0, ['blueberry', 'blueberries', 'توت', 'توت أزرق'], [opt('cup', 148)]),
  food('pineapple', 'Pineapple', 'أناناس', 'fruitFoods', 'g', 100, 50, 1, 13, 0, ['pineapple', 'أناناس']),
  food('kiwi', 'Kiwi', 'كيوي', 'fruitFoods', 'piece', 75, 46, 1, 11, 0, ['kiwi', 'كيوي'], [opt('piece', 75)]),

  food('spinach', 'Spinach', 'سبانخ', 'vegetableFoods', 'g', 100, 23, 3, 4, 0, ['spinach', 'سبانخ'], [opt('cup', 30)]),
  food('broccoli', 'Broccoli', 'بروكلي', 'vegetableFoods', 'g', 100, 35, 3, 7, 0, ['broccoli', 'بروكلي'], [opt('cup', 91)]),
  food('carrot', 'Carrot', 'جزر', 'vegetableFoods', 'g', 100, 41, 1, 10, 0, ['carrot', 'جزر']),
  food('bell-pepper', 'Bell pepper', 'فلفل رومي', 'vegetableFoods', 'g', 100, 31, 1, 6, 0, ['bell pepper', 'pepper', 'فلفل رومي', 'فلفل']),
  food('cucumber', 'Cucumber', 'خيار', 'vegetableFoods', 'g', 100, 15, 1, 4, 0, ['cucumber', 'خيار']),
  food('tomato', 'Tomato', 'طماطم', 'vegetableFoods', 'g', 100, 18, 1, 4, 0, ['tomato', 'طماطم', 'بندورة']),
  food('lettuce', 'Lettuce', 'خس', 'vegetableFoods', 'g', 100, 15, 1, 3, 0, ['lettuce', 'خس']),
  food('onion', 'Onion', 'بصل', 'vegetableFoods', 'g', 100, 40, 1, 9, 0, ['onion', 'بصل']),
  food('zucchini', 'Zucchini', 'كوسة', 'vegetableFoods', 'g', 100, 17, 1, 3, 0, ['zucchini', 'courgette', 'كوسة']),
  food('mushrooms', 'Mushrooms', 'فطر', 'vegetableFoods', 'g', 100, 22, 3, 3, 0, ['mushroom', 'mushrooms', 'فطر', 'مشروم']),
  food('mixed-vegetables', 'Mixed vegetables', 'خضار مشكلة', 'vegetableFoods', 'g', 100, 65, 3, 12, 1, ['mixed vegetables', 'vegetables', 'خضار', 'خضار مشكلة']),

  food('light-mayonnaise', 'Light mayonnaise', 'مايونيز لايت', 'sauceFoods', 'tbsp', 14, 35, 0, 1, 3, ['light mayo', 'light mayonnaise', 'mayo', 'مايونيز لايت', 'مايونيز'], [opt('tbsp', 14), opt('tsp', 4.7)]),
  food('hot-sauce', 'Hot sauce', 'شطة', 'sauceFoods', 'tbsp', 15, 5, 0, 1, 0, ['hot sauce', 'chili sauce', 'شطة', 'صوص حار'], [opt('tbsp', 15), opt('tsp', 5)]),
  food('maple-syrup', 'Maple syrup', 'شراب القيقب', 'sauceFoods', 'tbsp', 20, 52, 0, 13, 0, ['maple syrup', 'syrup', 'شراب القيقب'], [opt('tbsp', 20), opt('tsp', 6.7)]),

  food('green-tea', 'Green tea', 'شاي أخضر', 'drinkFoods', 'ml', 100, 1, 0, 0, 0, ['green tea', 'tea', 'شاي أخضر', 'شاي'], [opt('cup', 240)]),
  food('almond-milk', 'Almond milk', 'حليب لوز', 'drinkFoods', 'ml', 100, 15, 1, 1, 1, ['almond milk', 'milk alternative', 'حليب لوز'], [opt('cup', 240)]),
  food('soy-milk', 'Soy milk', 'حليب صويا', 'drinkFoods', 'ml', 100, 45, 3, 4, 2, ['soy milk', 'milk alternative', 'حليب صويا'], [opt('cup', 240)]),
  food('green-smoothie', 'Green smoothie', 'سموثي أخضر', 'drinkFoods', 'ml', 100, 45, 1, 9, 1, ['green smoothie', 'smoothie', 'سموثي', 'سموثي أخضر'], [opt('cup', 240), opt('serving', 300)]),

  food('creatine-monohydrate', 'Creatine monohydrate', 'كرياتين مونوهيدرات', 'supplementFoods', 'scoop', 5, 0, 0, 0, 0, ['creatine', 'creatine monohydrate', 'كرياتين', 'كرياتين مونوهيدرات'], [opt('scoop', 5), opt('serving', 5)]),
  food('bcaa-powder', 'BCAA powder', 'مسحوق BCAA', 'supplementFoods', 'scoop', 10, 10, 0, 0, 0, ['bcaa', 'amino acids', 'amino', 'امينو', 'مسحوق BCAA'], [opt('scoop', 10), opt('serving', 10)]),
  food('eaa-powder', 'EAAs powder', 'مسحوق EAA', 'supplementFoods', 'scoop', 10, 10, 0, 0, 0, ['eaa', 'eaas', 'amino acids', 'amino', 'امينو', 'مسحوق EAA'], [opt('scoop', 10), opt('serving', 10)]),
  food('pre-workout', 'Pre-workout', 'بري ووركاوت', 'supplementFoods', 'scoop', 12, 10, 0, 2, 0, ['pre-workout', 'preworkout', 'pre workout', 'بري ووركاوت'], [opt('scoop', 12), opt('serving', 12)]),
  food('multivitamin-tablet', 'Multivitamin tablet', 'حبة مالتي فيتامين', 'supplementFoods', 'piece', 1, 0, 0, 0, 0, ['multivitamin', 'vitamins', 'فيتامينات', 'مالتي فيتامين'], [opt('piece', 1)]),
  food('omega-3-capsule', 'Omega-3 capsule', 'كبسولة أوميغا 3', 'supplementFoods', 'piece', 1, 10, 0, 0, 1, ['omega 3', 'omega-3', 'اوميغا 3', 'أوميغا 3'], [opt('piece', 1)]),
  food('fish-oil-capsule', 'Fish oil capsule', 'كبسولة زيت السمك', 'supplementFoods', 'piece', 1, 10, 0, 0, 1, ['fish oil', 'omega 3', 'زيت السمك', 'اوميغا 3'], [opt('piece', 1)]),
  food('vitamin-d-tablet', 'Vitamin D tablet', 'حبة فيتامين د', 'supplementFoods', 'piece', 1, 0, 0, 0, 0, ['vitamin d', 'فيتامين د', 'فيتامين دي'], [opt('piece', 1)]),
  food('magnesium-tablet', 'Magnesium tablet', 'حبة مغنيسيوم', 'supplementFoods', 'piece', 1, 0, 0, 0, 0, ['magnesium', 'مغنيسيوم'], [opt('piece', 1)]),
  food('electrolytes-powder', 'Electrolytes powder', 'مسحوق إلكترولايت', 'supplementFoods', 'scoop', 5, 5, 0, 1, 0, ['electrolytes', 'electrolyte powder', 'إلكترولايت', 'الكترولايت'], [opt('scoop', 5), opt('serving', 5)]),
];
